version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.4.1
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  # promtail:
  #   image: grafana/promtail:2.4.1
  #   volumes:
  #     - /var/log:/var/log
  #   command: -config.file=/etc/promtail/config.yml

  # logstash:
  #   build:
  #     context: ./logstash
  #     dockerfile: "Dockerfile"
  #   volumes:
  #     - ./logstash/pipeline/pipelines.yml:/usr/share/logstash/config/pipelines.yml
  #     - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
  #     - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf

  #   ports:
  #     - "5044:5044"
  #     - "50000:50000/tcp"
  #     - "50000:50000/udp"
  #     - "9600:9600"
  #   environment:
  #     LS_JAVA_OPTS: -Xms256m -Xmx256m
  #     LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
  #   command: 'logstash -f /home/logstash/pipeline/loki.conf'
  #   networks:
  #     - loki
  #   depends_on:
  #     - loki
  
  logstash:
    image: grafana/logstash-output-loki:latest
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash_loki/pipeline/loki.conf:/home/logstash/loki.conf
    ports:
      - "5044:5044"
      - "50000:50000/tcp"
      - "50000:50000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
    command: 'logstash -f /home/logstash/loki.conf'
    networks:
      - loki
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - loki